[GLOBAL]
pants_version = "2.22.0"

# needed to make in-repo plugins work
pythonpath = ["%(buildroot)s/devtools"]

backend_packages = [
	"pants.backend.python",
	"pants.backend.python.lint.isort",
	"pants.backend.python.lint.flake8",
	"pants.backend.python.lint.autoflake",
	"pants.backend.experimental.adhoc",
	"radon.cc",
	"radon.mi",
	"prreqs",
]

[source]
root_patterns = [
	"src/",
	"/",
]

[python]
interpreter_constraints = ["CPython>=3.9"]
pip_version = "24.0"
enable_resolves = true

[python.resolves]
python-default = "devtools/python-default.lock"
flake8 = "devtools/flake8.lock"
radon = "devtools/radon.lock"

[isort]

[flake8]
install_from_resolve = "flake8"

[test]
extra_env_vars = [
	"DOCKER_HOST",
]
use_coverage=true
attempts_default = 3

[coverage-py]
report = ["xml", "html", "console"]
