python_sources()

python_requirements(
    name="reqs",
    source="docs_requirements.txt",
)

python_requirements(
    name="reqs0",
)

python_requirements(
    name="flake8",
    source="flake8_requirements.txt",
    resolve="flake8",
)
